FROM node:lts-buster-slim AS builder

RUN apt-get update && \
    apt-get install -y curl && \
    apt-get upgrade -y && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app
RUN npm install


FROM builder AS builder-with-snyk
COPY --from=snyk/snyk:linux /usr/local/bin/snyk /usr/local/bin/snyk
