FROM node:lts-buster-slim AS builder

RUN apt-get update && \
    apt-get install -y curl && \
    apt-get upgrade -y && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app
RUN npm install

FROM snyk/snyk:node-12 as snyk
WORKDIR app
COPY --from=builder app ./
CMD ["snyk", "test --json"]

